name:                imp
version:             0.1.0.0
github:              "jeffhappily/imp"
license:             BSD3
author:              "Jer Fei Cheah"
maintainer:          "goodboy96@live.com.my"
copyright:           "2020 Jer Fei Cheah"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeffhappily/imp#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- text
- bytestring
- containers

library:
  source-dirs: src
